version: '3.4'
services:
  db:
    image: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  web:
    restart: always
    depends_on:
      - db
    env_file:
      - ./.api.env
    build: .
    ports:
      - 3000:3000
